name: olivercoad-wcat
base: core18
version: '0.3.1'
summary: Send previews to your browser from the command line
description: |
  wcat is a webapp and cli tool which allows you to send previews of files to your
  browser while navigating a remote machine with ssh.
  Install this snap on the remote machine.

grade: stable
confinement: classic

apps:
  olivercoad-wcat:
    command: bin/wcat

  serve-wcat:
    command: sh -c "cd $SNAP/Server && $SNAP/dotnet Server.dll"
    daemon: simple

parts:
  dockerbuild:
    source: .
    source-type: local
    plugin: dump
    build-environment:
      # curl doesn't work without this
      - LD_PRELOAD: /usr/lib/x86_64-linux-gnu/libcurl.so.4
    override-build: |
      curl -fsSL https://get.docker.com -o get-docker.sh
      sh get-docker.sh
      export DOCKER_BUILDKIT=1
      docker build -t "wcat_snapcraft" .
      id=$(docker create wcat_snapcraft)
      docker cp $id:/Client $SNAPCRAFT_PART_INSTALL
      docker cp $id:/Server $SNAPCRAFT_PART_INSTALL
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      docker cp $id:/bin/wcat $SNAPCRAFT_PART_INSTALL/bin/wcat
    stage-snaps:
      - dotnet-sdk
